version: "3"
services:
  php:
    build: .
    image: "ali00h/php_mysql_backup_s3"
    container_name: php-mysql-backup-s3
    restart: always
    ports:
      - "8040:8080"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Pm123456
      - MYSQL_DATABASES=test_db
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - AWS_AccessKey=
      - AWS_SecretKey=
      - AWS_Bucket=
      - AWS_Endpoint=
      - AWS_Region=
      - AWS_BACKUP_DIRECTORY=dbbackup/mysql/
      - AWS_MAX_BACKUP_COUNT_FOR_EACH_DB=30
      - TIME_ZONE=Asia/Tehran
      - BACKUP_URL_SecretKey=123
      - CRON_URL_LIST=* * * * * https://example-files.online-convert.com/document/txt/example.txt
    networks:
      - pmbnetwork

networks:
  pmbnetwork:
    driver: bridge